/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StudentElection } from './StudentElection.js';
export * as factories from './factories/index.js';
export { StudentElection__factory } from './factories/StudentElection__factory.js';