/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StudentElection } from './StudentElection.js';
export type { Voting } from './Voting.js';
export * as factories from './factories/index.js';
export { StudentElection__factory } from './factories/StudentElection__factory.js';
export { Voting__factory } from './factories/Voting__factory.js';