/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace StudentElection {
      
    export type CandidateStruct = {name: string, position: string, department: string, voteCount: BigNumberish, walletAddress: AddressLike}

    export type CandidateStructOutput = [name: string, position: string, department: string, voteCount: bigint, walletAddress: string] & {name: string, position: string, department: string, voteCount: bigint, walletAddress: string }
  

    export type ElectionStruct = {id: BigNumberish, title: string, endTime: BigNumberish, isActive: boolean, creator: AddressLike}

    export type ElectionStructOutput = [id: bigint, title: string, endTime: bigint, isActive: boolean, creator: string] & {id: bigint, title: string, endTime: bigint, isActive: boolean, creator: string }
  
    }

  export interface StudentElectionInterface extends Interface {
    getFunction(nameOrSignature: "addCandidate" | "admin" | "alreadyVoted" | "createElection" | "electionCandidates" | "elections" | "endElection" | "getCandidateCount" | "getCandidates" | "getElection" | "getElectionCount" | "vote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CandidateAdded" | "ElectionCreated" | "VoteCast"): EventFragment;

    encodeFunctionData(functionFragment: 'addCandidate', values: [BigNumberish, string, string, string, AddressLike]): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'alreadyVoted', values: [BigNumberish, string, AddressLike]): string;
encodeFunctionData(functionFragment: 'createElection', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'electionCandidates', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'elections', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'endElection', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCandidateCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCandidates', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getElection', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getElectionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'alreadyVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'electionCandidates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'elections', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidateCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getElectionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  
    export namespace CandidateAddedEvent {
      export type InputTuple = [electionId: BigNumberish, name: string, position: string];
      export type OutputTuple = [electionId: bigint, name: string, position: string];
      export interface OutputObject {electionId: bigint, name: string, position: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ElectionCreatedEvent {
      export type InputTuple = [electionId: BigNumberish, title: string];
      export type OutputTuple = [electionId: bigint, title: string];
      export interface OutputObject {electionId: bigint, title: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [electionId: BigNumberish, position: string, voter: AddressLike, candidateId: BigNumberish];
      export type OutputTuple = [electionId: bigint, position: string, voter: string, candidateId: bigint];
      export interface OutputObject {electionId: bigint, position: string, voter: string, candidateId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface StudentElection extends BaseContract {
    
    connect(runner?: ContractRunner | null): StudentElection;
    waitForDeployment(): Promise<this>;

    interface: StudentElectionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addCandidate: TypedContractMethod<
      [electionId: BigNumberish, name: string, position: string, department: string, walletAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    alreadyVoted: TypedContractMethod<
      [arg0: BigNumberish, arg1: string, arg2: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    createElection: TypedContractMethod<
      [title: string, duration: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    electionCandidates: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, string, string, bigint, string] & {name: string, position: string, department: string, voteCount: bigint, walletAddress: string }],
      'view'
    >
    

    
    elections: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, boolean, string] & {id: bigint, title: string, endTime: bigint, isActive: boolean, creator: string }],
      'view'
    >
    

    
    endElection: TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getCandidateCount: TypedContractMethod<
      [electionId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getCandidates: TypedContractMethod<
      [electionId: BigNumberish, ],
      [StudentElection.CandidateStructOutput[]],
      'view'
    >
    

    
    getElection: TypedContractMethod<
      [electionId: BigNumberish, ],
      [StudentElection.ElectionStructOutput],
      'view'
    >
    

    
    getElectionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    vote: TypedContractMethod<
      [electionId: BigNumberish, candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addCandidate'): TypedContractMethod<
      [electionId: BigNumberish, name: string, position: string, department: string, walletAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'alreadyVoted'): TypedContractMethod<
      [arg0: BigNumberish, arg1: string, arg2: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'createElection'): TypedContractMethod<
      [title: string, duration: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'electionCandidates'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, string, string, bigint, string] & {name: string, position: string, department: string, voteCount: bigint, walletAddress: string }],
      'view'
    >;
getFunction(nameOrSignature: 'elections'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, boolean, string] & {id: bigint, title: string, endTime: bigint, isActive: boolean, creator: string }],
      'view'
    >;
getFunction(nameOrSignature: 'endElection'): TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCandidateCount'): TypedContractMethod<
      [electionId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCandidates'): TypedContractMethod<
      [electionId: BigNumberish, ],
      [StudentElection.CandidateStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getElection'): TypedContractMethod<
      [electionId: BigNumberish, ],
      [StudentElection.ElectionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getElectionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [electionId: BigNumberish, candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CandidateAdded'): TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
getEvent(key: 'ElectionCreated'): TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;

    filters: {
      
      'CandidateAdded(uint256,string,string)': TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
      CandidateAdded: TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
    

      'ElectionCreated(uint256,string)': TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
      ElectionCreated: TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
    

      'VoteCast(uint256,string,address,uint256)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    
    };
  }