/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { StudentElection__factory } from './StudentElection__factory.js';
export { Voting__factory } from './Voting__factory.js';